version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - ./volumes/nginx-proxy/vhost:/etc/nginx/vhost.d:rw
      - ./volumes/nginx-proxy/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      LETSENCRYPT_HOST: owncloud.cotne.com
      LETSENCRYPT_EMAIL: cotne.95@gmail.com

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ./volumes/nginx-proxy/certs:/etc/nginx/certs:rw
      - ./volumes/nginx-proxy/vhost:/etc/nginx/vhost.d:rw
      - ./volumes/nginx-proxy/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

  owncloud:
    image: owncloud
    volumes:
      - ./volumes/owncloud:/var/www/html:rw
    environment:
      VIRTUAL_HOST: owncloud.cotne.com

  mysql:
    image: mariadb
    volumes:
      - ./volumes/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
