#!/usr/bin/env bash
set -e

if [ ! -f ./node_modules/@thecotne/tasker/tasker-core ]; then
    yarn
fi

source ./node_modules/@thecotne/tasker/tasker-core

function start { # start docker stack
    prepare-volumes
    docker stack deploy -c stack.yml owncloud
}

function stop { # rm docker stack
    docker stack rm owncloud
}

function prepare-volumes { # prepare volumes
    mkdir -p volumes/mysql
    mkdir -p volumes/owncloud
    mkdir -p volumes/nginx-proxy/certs
    mkdir -p volumes/nginx-proxy/vhost
    mkdir -p volumes/nginx-proxy/html
}

function clean { # clean volumes
    rm -rf ./volumes
    prepare-volumes
}

_bootstrap "${@}"
